name: Laravel Tests (MySQL)

on:
  pull_request:
    branches: [ main ]

jobs:
  mysql-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -uuser -ppassword" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pdo, pdo_mysql, bcmath, ctype, fileinfo, json, tokenizer, xml, intl

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache/files
        key: ${{ runner.os }}-composer-v4-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-v4-

    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
        cp .env.example .env
        php artisan key:generate

    - name: Execute tests with MySQL
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_db
        DB_USERNAME: user
        DB_PASSWORD: password
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        php artisan migrate:fresh --seed --force
        composer test
